version: 2

# List of jobs
jobs:
    # The install job
    install:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.12
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v2-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules

    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.12
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run compile
            - run:
                name: Truffle compile
                command: node_modules/.bin/truffle compile
            # Save build
            - store_artifacts:
                path: build

    # The test job
    test:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.12
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Create migrations folder
            - run:
                name: Create migrations folder
                command: mkdir migrations
            # Start ganache
            - run:
                name: Start ganache instance
                command: |
                    node_modules/.bin/ganache-cli \
                    --hardfork petersburg \
                    --account '0xced26e4f0ad256777efa4b205ac3003eca7e1befb9f657be58600b7115a6cdf1,100000000000000000000' \
                    --account '0x3132ce18b38230af1f8d751f5658c97e59d33a9e884676fddfc9cc4434cd36fb,100000000000000000000' \
                    --account '0x087df46b73931fd31751e80a203bb6be011f3ab2cf1930b2a92db901f0fdffc6,100000000000000000000' \
                    --account '0xeb558208fc7e52bc018d11414e6e624d0ab44a7cb63dfad9d75f913b45268746,100000000000000000000' \
                    --account '0xde43de7119a20ee767b39b926058096f95812058ed1c078f35269b5c788a33cf,100000000000000000000'
                background: true
            # Run truffle test
            - run:
                name: Run truffle tests
                command: node_modules/.bin/truffle test

    # The lint-javascript job
    lint-javascript:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.12
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run lint javascript
            - run:
                name: ESLint
                command: ./node_modules/.bin/eslint .

    # The lint-solidity job
    lint-solidity:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.12
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run Solidity lint
            - run:
                name: Solhint
                command: ./node_modules/.bin/solhint \"contracts/**/*.sol\"

workflows:
    version: 2
    # The build and deploy workflow
    build_and_test:
        jobs:
            - install
            - build:
                requires:
                    - install
            - test:
                requires:
                    - install
            - lint-javascript:
                requires:
                    - install
            - lint-solidity:
                requires:
                    - install
